version: "3.7"

services:
  traefik:
    image: traefik
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
      - 8080:8080

  gitlab:
    image: gitlab/gitlab-ce:13.1.4-ce.0
    restart: always
    ports:
      - "5000:80"
      - "5001:443"
      - "5002:22"
    volumes:
      - gitlab_config:/etc/gitlab
      - gitlab_data:/var/opt/gitlab
      - gitlab_log:/var/log/gitlab
    deploy:
      resources:
        limits:
          memory: 1024M
          cpus: "1"

  jenkins:
    image: lucastercas/jenkins
    restart: always
    build:
      context: jenkins
    ports:
      - "4000:8080"
    volumes:
      - jenkins_data:/var/jenkins_home
      - jenkins_docker_certs:/certs/client
    environment:
      DOCKER_HOST: "tcp://docker:2376"
      DOCKER_CERT_PATH: "/certs/client"
      DOCKER_TLS_VERIFY: 1
      DOCKER_USER: ${DOCKER_USER}
      DOCKER_PASSWORD: ${DOCKER_PASSWORD}
      SONAR_TOKEN: ${SONAR_TOKEN}
    deploy:
      resources:
        limits:
          memory: 1024M
          cpus: "1"

  docker:
    image: docker:19.03.12-dind
    restart: always
    privileged: true
    volumes:
      - jenkins_data:/var/jenkins_home
      - jenkins_docker_certs:/certs/client
      environment:
        DOCKER_TLS_CERTDIR: /certs
    deploy:
      resources:
        limits:
          memory: 1024M
          cpus: "1"

  sonarqube:
    image: sonarqube:8.4.0-community
    restart: always
    ports:
      - "7000:9000"
    volumes:
      - sonarqube_data:/opt/sonarqube/data
    deploy:
      resources:
        limits:
          memory: 1024M
          cpus: "1"

volumes:
  gitlab_config:
    driver: local
  gitlab_log:
    driver: local
  gitlab_data:
    driver: local
  jenkins_data:
    driver: local
  jenkins_docker_certs:
    driver: local
  sonarqube_data:
    driver: local