version: "3.8"

services:
  gitlab:
    image: gitlab/gitlab-ce:13.1.4-ce.0
    restart: always
    ports:
      - "2000:80"
    volumes:
      - gitlab-config:/etc/gitlab
      - gitlab-data:/var/opt/gitlab
    deploy:
      replicas: 1
      resources:
        limits:
          memory: 1024M
          cpus: "1"
      restart_policy:
        condition: on-failure

  jenkins:
    image: lucastercas/jenkins
    restart: always
    ports:
      - 3000:5000
      - 3001:8080
    volumes:
      - jenkins-data:/var/jenkins/home
      - docker-certs:/certs/client
    environment:
      DOCKER_HOST: "tcp://docker:2376"
      DOCKER_CERT_PATH: "/certs/client"
      DOCKER_TLS_VERIFY: 1
      DOCKER_USER: ${DOCKER_HUB_USER}
      DOCKER_PASSWORD: ${DOCKER_HUB_PASSWORD}
      SONAR_TOKEN: ${SONAR_TOKEN}
    deploy:
      replicas: 1
      resources:
        limits:
          memory: 1024M
          cpus: "1"
      restart_policy:
        condition: on-failure

  docker:
    image: docker:19.03.12-dind
    restart: always
    privileged: true
    volumes:
      - jenkins-data:/var/jenkins_home
      - docker-certs:/certs/client
    environment:
      DOCKER_TLS_CERTDIR: /certs
    deploy:
      resources:
        limits:
          memory: 1024M
          cpus: "1"

  sonarqube:
    image: sonarqube:8.4.0-community
    ports:
      - 4000:9000
    volumes:
      - sonar-data:/opt/sonarqube/data
    deploy:
      replicas: 1
      resources:
        limits:
          memory: 1024M
          cpus: "1"
      restart_policy:
        condition: on-failure

volumes:
  jenkins-data:
  docker-certs:
  gitlab-config:
  gitlab-data:
  sonar-data:

