pipeline {
    agent {
        docker {
            image 'maven:3-alpine' 
            args '-v /root/.m2:/root/.m2' 
        }
    }
    environment {
        DOCKER_USER = 'lucastercas'
        DOCKER_PASSWORD = 'deZzBU4/@2'
        PROJECT_KEY = 'org.springframework:gs-spring-boot-docker'
        SONAR_LOGIN = 'e6f696687d9b343872358aaf19371fe5dfdca63f'
        SONAR_URL = 'http://sonarqube'
    }
    options {
        skipStagesAfterUnstable()
    }
    stages {
        stage('Build') { 
            steps {
                sh 'mvn -B -DskipTests clean package' 
            }
        }
        stage('Test') {
            steps {
                sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Sonarqube') {
            agent none
            steps {
                sh "mvn sonar:sonar -Dsonar.projectKey=${PROJECT_KEY} -Dsonar.host.url=${SONAR_URL} -Dsonar.login=${SONAR_LOGIN}"
            }
        }
        stage('Docker Login') {
            steps {
                sh 'echo docker login'
            }
        }
        stage('Push Image') {
            steps {
                sh 'echo pushing image'
            }
        }
    }
    post {
        always {
            archiveArtifacts artifacts: "target/*.jar", fingerprint: true
        }
    }
}